Repository jingni1115/Petmily, pull requests merged in 2023-11, with the labels that each got.

#19 [DESIGN] : 🎨 floating tabbar 설정 완료 / basetabbarcontroller 삭제
  Petmily/Petmily.xcodeproj/project.pbxproj
  Petmily/Petmily/AppDelegate.swift
  Petmily/Petmily/Assets.xcassets/tabbar/Contents.json
  Petmily/Petmily/Assets.xcassets/tabbar/tab_daily.imageset/Contents.json
  Petmily/Petmily/Assets.xcassets/tabbar/tab_daily.imageset/tab_daily.png
  Petmily/Petmily/Assets.xcassets/tabbar/tab_daily_selected.imageset/Contents.json
  Petmily/Petmily/Assets.xcassets/tabbar/tab_daily_selected.imageset/tab_daily_selected.png
  Petmily/Petmily/Assets.xcassets/tabbar/tab_info.imageset/Contents.json
  Petmily/Petmily/Assets.xcassets/tabbar/tab_info.imageset/tab_info.png
  Petmily/Petmily/Assets.xcassets/tabbar/tab_info_selected.imageset/Contents.json
  Petmily/Petmily/Assets.xcassets/tabbar/tab_info_selected.imageset/tab_info_selected.png
  Petmily/Petmily/Assets.xcassets/tabbar/tab_location.imageset/Contents.json
  Petmily/Petmily/Assets.xcassets/tabbar/tab_location.imageset/tab_location.png
  Petmily/Petmily/Assets.xcassets/tabbar/tab_location_selected.imageset/Contents.json
  Petmily/Petmily/Assets.xcassets/tabbar/tab_location_selected.imageset/tab_location_selected.png
  Petmily/Petmily/Assets.xcassets/tabbar/tab_my.imageset/Contents.json
  Petmily/Petmily/Assets.xcassets/tabbar/tab_my.imageset/tab_my.png
  Petmily/Petmily/Assets.xcassets/tabbar/tab_my_selected.imageset/Contents.json
  Petmily/Petmily/Assets.xcassets/tabbar/tab_my_selected.imageset/tab_my_selected.png
  Petmily/Petmily/ViewControllers/Base/BaseTabbarController.swift
  Petmily/Petmily/ViewControllers/Base/TabBarController.swift
  Petmily/Petmily/ViewControllers/Base/TabBarView.swift
  Petmily/Petmily/ViewControllers/Tabbar/AddViewController.swift
Labels: [DESIGN] : 🎨

#25 [글쓰기 페이지] UI 작성
  Petmily/Petmily.xcodeproj/project.pbxproj
  Petmily/Petmily/New Group/NewPostPage.swift
  Petmily/Petmily/ViewControllers/Tabbar/DailyViewController.xib
Labels: [DESIGN] : 🎨

#26 [FIX]: tabbar 옮길 때 앞에 뷰 모두 제거
  Petmily/Petmily/ViewControllers/Base/TabBarController.swift
Labels: bug

#30 Feat/daily
  Petmily/Petmily.xcodeproj/project.pbxproj
  Petmily/Petmily/Network/CacheManager.swift
  Petmily/Petmily/ViewControllers/Tabbar/CameraViewController.swift
  Petmily/Petmily/ViewControllers/Tabbar/DailyViewController.swift
  Petmily/Petmily/ViewControllers/Tabbar/DailyViewController.xib
Labels: enhancement, [DESIGN] : 🎨

#38 로그인 화면 UI 작성, SnapKit 코드 수정
  Petmily/Petmily.xcodeproj/project.pbxproj
  Petmily/Petmily/ViewControllers/Login/loginViewController.swift
  Petmily/Petmily/ViewControllers/New Group/NewPostPage.swift
Labels: [DESIGN] : 🎨
